
services:

  gcp-storage:
    image: gcp-storage
    build: 
      context: ./gcp-storage
      dockerfile: Dockerfile
    container_name: video-storage
    ports:
     - "4001:80"
    environment:
      - PORT=80
      - GCS_BUCKET_NAME=video_streaming_cloud_project
    volumes:
      - cloud-project-444314-415018942b9b.json
    restart: "no"

  video-streaming:
    image: video-streaming
    build: 
      context: ./video-streaming
      dockerfile: Dockerfile
    container_name: video-streaming
    ports:
     - "4002:80"
    environment:
      - PORT=80
      - DBHOST=mongodb://host.docker.internal:27017  
      - DBNAME=video_service
      - VIDEO_STORAGE_HOST=video-storage  
      - VIDEO_STORAGE_PORT=80 
      - GOOGLE_APPLICATION_CREDENTIALS=cloud-project-444314-415018942b9b.json 
    restart: "no"
